### PR TITLE
ENH: added default argument support

### PR DESCRIPTION
**Pull request by BenKaehler**
I've added support for Bool primitive in the [standard click way](http://click.pocoo.org/5/options/#boolean-flags). There are other ways to do it, so please let me know if you would like something different.

### CODE REVIEW

**Comment by BenKaehler** [comment]
Oops, should have referenced #52, sorry. I didn't check the issues.

**Comment by thermokarst** [comment]
Thanks @BenKaehler! Do you think you could update your fork (maybe rebase it) so that all of the noise in the diff is cut out? It looks like something got messed up in the history. Thanks!

**Comment by BenKaehler** [comment]
Thanks @thermokarst, I've rebased, which seems to have fixed the diff, at least.

**Comment by BenKaehler** [comment]
Hi @thermokarst, I've added default parameters, which required some changes to qiime2 (under guidance from @ebolyen). CI will fail unless this [pull request](https://github.com/qiime2/qiime2/pull/125) is accepted, so I'll let you know if or when it goes through. Thanks!

**Comment by ebolyen** [comment]
Hey @BenKaehler could you put the defaults in a separate PR? Thanks for getting started on that, but it will require some deeper coordination between the packages. If they are separate PRs we should be able to merge the `bool` functionality faster.

**Comment by BenKaehler** [comment]
Hi @ebolyen, I've branched the bool commit and made a separate pull request for it here #55.

**Comment by thermokarst** [comment]
Thanks @BenKaehler for opening up #55! Can you make sure to update this PR so that the `defaults` work is not included here, and only in #55? We are hoping to get these `bool` changes  merged in as soon as possible, and it sounds like the `defaults` changes can potentially hold that up. So basically the PR will look like what you had in ea44ac5. Sorry for all the back and forth! Let me know if I can help with anything. Otherwise, this looks like it will be really straightforward to get rolled in. Thanks again!

**Comment by BenKaehler** [comment]
Hi @thermokarst, my git-fu isn't that awesome, but I think that #55 contains only the `bool` changes, and this pull request should contain the `defaults` changes (which overwrite the `bool` changes anyway). Could you please use #55 to merge the `bool` changes? Also, I've changed the title of this pull request to reflect the changes.

**Comment by jairideout** [comment]
Thanks @BenKaehler! We'll work on getting #55 merged first and then will review this one along with https://github.com/qiime2/qiime2/pull/125

**Comment by jairideout** [comment]
@BenKaehler this looks good! Can you please fix the merge conflicts? There's also some extra changes that have already been merged upstream (source format and bool support). Not sure what's going on there, maybe they'll disappear when the merge conflicts are resolved. Let me know when you're ready and I'll take a final pass through.

**Comment by BenKaehler** [comment]
Thanks @jairideout, a rebase appears to have fixed it. Fingers crossed the checks will pass when qiime2/qiime2#125 is committed.

**Comment by jairideout** [comment]
Thanks @BenKaehler, looks great! The test failures were unrelated to your changes, I fixed them in #62. I just reran the tests and they passed.

**Pull request merged**
