### PR TITLE
BUG: stop swallowing certain Result errors

### LINKED ISSUE #240: Conflicting packages in a conda environment cause confusing errors
**Bug Description**
Having packages installed that conflict with other installed plugins' requirements seems to cause most actions in QIIME 2 to fail. While failure isn't necessarily unexpected behavior in this situation, the error messages seem pretty confusing -- it took me a decent amount of struggling to figure out what the problem was, and I expect other users will also fall into this problem eventually.

**Steps to reproduce the behavior**
1. In a QIIME 2 conda environment (I've tested this on QIIME 2 2019.10), `pip`-install a version of a package that deliberately conflicts with what's specified in a Q2 plugin's `setup.py`. For example, installing `pandas==1.0.3` in a environment where [Qurro](https://library.qiime2.org/plugins/qurro/22/) is installed (since Qurro requires that a pandas version that satisfies `"pandas >= 0.24.0, <1"` is installed).
2. Try to run -- what seems to me -- basically any Q2 plugin within the now-"unsatisfiable" QIIME 2 environment. Here I'll use `qiime taxa barplot` as an example, but I've observed this with other plugins.

```bash
qiime taxa barplot \
    --i-table table.qza \
    --i-taxonomy taxonomy.qza \
    --m-metadata-file metadata.txt \
    --o-visualization tbp.qzv
```

This triggers the following error:

```
Usage: qiime taxa barplot [OPTIONS]

  This visualizer produces an interactive barplot visualization of
  taxonomies. Interactive features include multi-level sorting, plot
  recoloring, sample relabeling, and SVG figure export.

Inputs:
  --i-table ARTIFACT FeatureTable[Frequency]
                         Feature table to visualize at various taxonomic
                         levels.                                    [required]
  --i-taxonomy ARTIFACT FeatureData[Taxonomy]
                         Taxonomic annotations for features in the provided
                         feature table. All features in the feature table must
                         have a corresponding taxonomic annotation. Taxonomic
                         annotations that are not present in the feature table
                         will be ignored.                           [required]
Parameters:
  --m-metadata-file METADATA...
    (multiple            The sample metadata.
     arguments will be   
     merged)                                                        [required]
Outputs:
  --o-visualization VISUALIZATION
                                                                    [required]
Miscellaneous:
  --output-dir PATH      Output unspecified results to a directory
  --verbose / --quiet    Display verbose output to stdout and/or stderr
                         during execution of this action. Or silence output if
                         execution is successful (silence is golden).
  --citations            Show citations and exit.
  --help                 Show this message and exit.

                  There were some problems with the command:                  
 (1/2) Invalid value for "--i-table": 'table.qza' is not a QIIME 2 Artifact
  (.qza)
 (2/2) Invalid value for "--i-taxonomy": 'taxonomy.qza' is not a QIIME 2
  Artifact (.qza)
```

Normally I'd expect this to be due to these QZAs not existing in the specified location or being invalid or something, but these QZAs really are "normal". The cause of the problem is revealed when you try to validate these QZAs:

```bash
qiime tools validate table.qza
```

gives you

```
Traceback (most recent call last):
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/q2cli/builtin/tools.py", line 409, in validate
    result = qiime2.sdk.Result.load(path)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/result.py", line 66, in load
    archiver = archive.Archiver.load(filepath)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 307, in load
    return cls(path, Format(rec))
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/format/v1.py", line 29, in __init__
    super().__init__(archive_record)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/format/v0.py", line 73, in __init__
    self.format = sdk.parse_format(format)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/util.py", line 88, in parse_format
    pm = qiime2.sdk.PluginManager()
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

There was a problem loading table.qza as a QIIME 2 Result:

  (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

See above for debug info.
```

As the error message implies, installing a "sane" version of pandas (`pip install pandas==0.25.2`) fixes the problem, allowing both `qiime tools validate` and the `qiime taxa barplot` command to work.

**Expected behavior**
Rather than the `qiime taxa barplot` command (or other plugins) telling the user that the input QZAs are each "`not a QIIME 2 Artifact (.qza)`", a more informative error message should be returned that explains that the environment is somehow invalid (sort of like the `qiime tools validate` command gives you).

**Computation Environment**
- OS: Ubuntu 18.04.3
- QIIME 2 Release 2019.10
- Using the `fish` terminal, if that helps

**Comments**
1. I'm guessing that when the QIIME 2 internals try to load a QZA, some sort of environment "satisfiability" check is performed -- either directly or indirectly -- and this check failing is taken to mean that the QZAs are invalid. However, in this case, the QZAs _are_ valid: so the reported error message is misleading to users.

Thanks!

### PR DESCRIPTION
**Pull request by thermokarst**
Fixes #240 

@ebolyen - I could use a hand on this, if you get a chance - I'm not sure what the "right" way is to report the traceback back to the user. I hacked something into place, but I have a hunch there is a better way...

### CODE REVIEW

**Comment by thermokarst** [comment]
Pinging @fedarko - do you have a minute today to look at this? Just want to double-check that this addresses the issue you brought up in #240. If you don't have time, no worries. Thanks!

**Comment by Oddant1** [comment]
In attempting to review this I found myself unable to reproduce the error message indicated in #240 using qiime2 2020.2. I made sure I didn't have this PR checked out and installed when testing. I used the following steps

1. Create new 2020.2 environment

2. Run `emp-single` command from Moving Pictures to ensure functionality

3. Pip install qurro

4. Rerun 2 just to be sure

5. pip install pandas==1.0.3

6. Attempt to rerun 2 and get the following
___
image
___

When I attempted the above with a Qiime2 2019.10 install as discussed in #240 I did get the `not a qza` error, but it doesn't seem to happen in 2020.2.

**Comment by thermokarst** [comment]
Thanks @Oddant1!

> but it doesn't seem to happen in 2020.2.

Your screenshot above indicates that this _might_ be a 2020.2 environment (at least it has 2020.2 in the env name), though - or is there some difference in the error message that I'm missing?

**Comment by fedarko** [comment]
@thermokarst Sorry for getting to this late in the day. I created a new environment based on the dev version of QIIME 2 from [here](https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml) and modified `[conda envs path]/qiime2-dev-20200623/lib/python3.6/site-packages/q2cli/click/type.py` to match your changes from this PR. Then verified that, after installing Qurro 0.7.1 and pandas 1.0.3, the error message I got upon running `qiime taxa barplot` was as expected:

```
marcus@ultraviolet ~/D/W/K/m/data> qiime taxa barplot \                                                                                                (qiime2-dev-20200623) 
                                       --i-table table.qza \
                                       --i-taxonomy taxonomy.qza \
                                       --m-metadata-file sample-metadata.tsv \
                                       --o-visualization tbp.qzv
Traceback (most recent call last):
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/q2cli/click/type.py", line 112, in _convert_input
    result = qiime2.sdk.Result.load(value)
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/sdk/result.py", line 66, in load
    archiver = archive.Archiver.load(filepath)
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 307, in load
    return cls(path, Format(rec))
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/core/archive/format/v1.py", line 29, in __init__
    super().__init__(archive_record)
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/core/archive/format/v0.py", line 73, in __init__
    self.format = sdk.parse_format(format)
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/sdk/util.py", line 88, in parse_format
    pm = qiime2.sdk.PluginManager()
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 54, in __new__
    self._init(add_plugins=add_plugins)
  File "/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 81, in _init
    plugin = entry_point.load()
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

There was a problem loading table.qza as a QIIME 2 Result:

  (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-dev-20200623/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

See above for debug info.
```

I think the screenshot @Oddant1 posted is different from the one I was getting with Q2 2019.10 in that his error message is specific about the cause (the pandas version is unacceptable), while the one I was getting in #240 was more cryptic (complaining about the QZAs not being valid even though they were valid). Before I applied the `q2cli` fixes in the dev version of Q2, I noticed that messing with the pandas version caused the same error @Oddant1 shows above -- so it seems like the root of the problem was something in Q2 2019.10 that has since been resolved.

For comparison's sake, I also tried applying the q2cli fixes to my Q2 2019.10 environment (I first reinstalled pandas to a correct version (v0.25.2) so I could run `qiime dev refresh-cache` without that exploding). Verified that, after re-re-installing pandas to v1.0.3, the q2cli fixes caused the correct error to be shown:

```
marcus@ultraviolet ~/D/W/K/m/data> qiime taxa barplot \                                                                                                     (qiime2-2019.10) 
                                       --i-table table.qza \
                                       --i-taxonomy taxonomy.qza \
                                       --m-metadata-file sample-metadata.tsv \
                                       --o-visualization tbp.qzv
/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/skbio/util/_testing.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as pdt
Traceback (most recent call last):
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/q2cli/click/type.py", line 112, in _convert_input
    result = qiime2.sdk.Result.load(value)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/result.py", line 66, in load
    archiver = archive.Archiver.load(filepath)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 307, in load
    return cls(path, Format(rec))
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/format/v1.py", line 29, in __init__
    super().__init__(archive_record)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/format/v0.py", line 73, in __init__
    self.format = sdk.parse_format(format)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/util.py", line 88, in parse_format
    pm = qiime2.sdk.PluginManager()
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

There was a problem loading table.qza as a QIIME 2 Result:

  (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

See above for debug info.
```

So... it looks like these fixes solve the problem, even though Q2 2020.2 apparently already partially solved the problem anyway? Not sure what changed in 2020.2, but things seem solid to me in any case :tada:

**Comment by thermokarst** [comment]
Great, thanks so much for taking a peek, @fedarko!

**Pull request merged**
