### PR TITLE
`short_description` and `description` in output

### PR DESCRIPTION
**Pull request by maxvonhippel**
Added `short_description` of each installed plugin to print statement from `qiime info` output, and `description` from any given plugin to the output from running `qiime --help name-of-that-plugin`.

A simple test example can be seen in the output quoted [in my pull request to `q2-feature-table`](https://github.com/qiime2/q2-feature-table/pull/91).

### CODE REVIEW

**Comment by maxvonhippel** [comment]
@jairideout right, sorry I didn't read your comment carefully the first time.  I'll fix it a bit later this week.  Thanks!

**Comment by jairideout** [comment]
No worries, thanks @maxvonhippel! Just ping me on this PR when it's ready for review.

**Comment by maxvonhippel** [comment]
Sample outputs:

1. **info**
````BASH
(qiime2-dev) ➜  ~ qiime info
QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
System versions
Python version: 3.5.2
QIIME 2 version: 2017.3.0.dev0
q2cli version: 2017.3.0.dev0

Installed plugins
feature-table 2017.3.0.dev0
types 2017.3.0.dev0

Application config directory
/Users/maxvonhippel/Library/Application Support/q2cli

Getting help
To get help with QIIME 2, visit https://qiime2.org

Citing QIIME 2
If you use QIIME 2 in any published work, you should cite QIIME 2 and the plugins that you used. To display the citations for QIIME 2 and all installed plugins, run:

  qiime info --citations
````

2. **help**
````BASH
(qiime2-dev) ➜  ~ qiime --help
Usage: qiime [OPTIONS] COMMAND [ARGS]...

  QIIME 2 command-line interface (q2cli)
  --------------------------------------

  To get help with QIIME 2, visit https://qiime2.org.

  To enable tab completion in Bash, run the following command or add it to
  your .bashrc/.bash_profile:

      source tab-qiime

  To enable tab completion in ZSH, run the following commands or add them to
  your .zshrc:

      autoload bashcompinit && bashcompinit && source tab-qiime

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  info           Display information about current deployment.
  tools          Tools for working with QIIME 2 files.
  dev            Utilities for developers and advanced users.
  feature-table  Plugin for working with sample x feature tables.
````

3. **plugin help**
````BASH
(qiime2-dev) ➜  ~ qiime feature-table --help
Usage: qiime feature-table [OPTIONS] COMMAND [ARGS]...

  Description: This is a QIIME 2 plugin supporting operations on sample x
  feature tables, such as filtering, merging, and transforming tables.

  Plugin website: https://github.com/qiime2/q2-feature-table

  Getting user support: No user support information available. See plugin
  website: https://github.com/qiime2/q2-feature-table

  Citing this plugin: The Biological Observation Matrix (BIOM) format or:
  how I learned to stop worrying and love the ome-ome. Daniel McDonald, Jose
  C Clemente, Justin Kuczynski, Jai Ram Rideout, Jesse Stombaugh, Doug
  Wendel, Andreas Wilke, Susan Huse, John Hufnagle, Folker Meyer, Rob Knight
  and J Gregory Caporaso. GigaScience 1:7 (2012).doi:10.1186/2047-217X-1-7

Options:
  --help  Show this message and exit.

Commands:
  filter-features     Filter features from table.
  filter-samples      Filter samples from table.
  merge               Combine two tables
  merge-seq-data      Combine two collections of feature sequences
  merge-taxa-data     Combine two collections of feature taxonomies
  presence-absence    Convert to presence/absence
  rarefy              Rarefy table
  relative-frequency  Convert to relative frequencies
  summarize           Summarize table
  tabulate-seqs       View sequence associated with each feature
````

**Comment by maxvonhippel** [comment]
(So I removed plugin descriptions, short or otherwise, from info, made help use short descriptions, and added long descriptions to plugin help.  If you'd like the long description format to be different in plugin help let me know!)

**Comment by maxvonhippel** [comment]
Awesome!  I had fun working on this, `q2cli` is really well organized and the click library is an interesting one I'd never worked with before.  Looking forward to getting started on the docs!  Thanks!

**Pull request merged**
