### PR TITLE
update replay supplement tests for nested zipfile directory

### PR DESCRIPTION
**Pull request by colinvwood**
updates for qiime2/qiime2#732

### CODE REVIEW

**Comment by colinvwood** [comment]
~~blocked by qiime2/qiime2#732~~

**Review by gregcaporaso — APPROVED** [review]
Looks good, ready for merge once the tests pass. Thanks @colinvwood!

**Comment by lizgehret** [comment]
@gregcaporaso @colinvwood test failures are due to CI not pulling the latest version of qiime2 that contains the requisite changes that this PR depends on. @ebolyen is working on a fix for this, but in the meantime if you can confirm that these tests pass on both osx and ubuntu (testing locally), this should be good to merge.

**EDIT**: @gregcaporaso you mentioned that you'd already tested this locally on osx, so we should just have this tested on ubuntu before merging. @Oddant1 can you pull this down with the requisite framework changes and confirm that tests pass locally?

**Comment by gregcaporaso** [comment]
Thanks @lizgehret and @ebolyen! I just confirmed again that the q2cli tests pass locally for me when working with the latest dev branch of the framework.

**Comment by colinvwood** [comment]
there's no rush to merge this, these are just tests for a small change in the framework... I guess CI will fail here until this is merged though

**Comment by Oddant1** [comment]
@lizgehret tests passed for me

**Comment by lizgehret** [comment]
Okay @gregcaporaso this should be good to merge!

**Pull request merged**
